# Generated by Django 5.0.6 on 2024-07-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_books_image_alter_books_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(null=True, upload_to='book/'),
        ),
    ]
